services:
  pgsql:
    image: postgres:17.2-alpine
    hostname: pgsql
    container_name: pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${DB_NAME:-postgres}"
      POSTGRES_USER: "${DB_USER:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-postgres}"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - pgsql:/var/lib/postgresql/data

volumes:
  pgsql:
    name: artel-pgsql